### ISSUE TITLE
能否添加油猴菜单的触发方式？

### ISSUE THREAD

**Issue by cxyzzz** [NoCLin/WebAppify#1]
如题，手机上使用没法右键触发，能否通过油猴菜单来触发？

**Comment by NoCLin** [comment]
你用的是什么浏览器？我在电脑版本可以通过点击Tampermonkey的按钮显示右键菜单，手机Kiwi浏览器也可以在菜单栏找到Tampermonkey按钮。

What browser are you using? On the desktop version, I can see the context-menu by clicking on the Tampermonkey button. On the mobile Kiwi browser, I can also find the Tampermonkey button in the menu bar.

<img width="345" src="https://github.com/NoCLin/WebAppify/assets/31406718/eb7d914b-249f-400b-96b6-aa93e67c37e6">

**Comment by cxyzzz** [comment]
> 你用的是什么浏览器？我在电脑版本可以通过点击Tampermonkey的按钮显示右键菜单，手机Kiwi浏览器也可以在菜单栏找到Tampermonkey按钮。
> 
> What browser are you using? On the desktop version, I can see the context-menu by clicking on the Tampermonkey button. On the mobile Kiwi browser, I can also find the Tampermonkey button in the menu bar.
> 
> <img alt="" width="345" src="https://user-images.githubusercontent.com/31406718/243091886-eb7d914b-249f-400b-96b6-aa93e67c37e6.png">

咦，我也用的kivi但没有菜单，不过我是用的暴力猴beta最新版本，我试试油猴。kivi版本：112.0.5615.137，暴力猴beta版本:2.14.2

**Comment by cxyzzz** [comment]
> > 你用的是什么浏览器？我在电脑版本可以通过点击Tampermonkey的按钮显示右键菜单，手机Kiwi浏览器也可以在菜单栏找到Tampermonkey按钮。
> > What browser are you using? On the desktop version, I can see the context-menu by clicking on the Tampermonkey button. On the mobile Kiwi browser, I can also find the Tampermonkey button in the menu bar.
> > <img alt="" width="345" src="https://user-images.githubusercontent.com/31406718/243091886-eb7d914b-249f-400b-96b6-aa93e67c37e6.png">
> 
> 咦，我也用的kivi但没有菜单，不过我是用的暴力猴beta最新版本，我试试油猴。kivi版本：112.0.5615.137，暴力猴beta版本:2.14.2

油猴（篡改猴能显示）

**Comment by NoCLin** [comment]
我本地测试修复了（Tampermonkey + Violentmonkey），你再检查一下看看？

关键代码：https://github.com/NoCLin/WebAppify/blob/4d1633418ca2db617fe3cb109e9a8cbd8b4cae75/WebAppify.user.js#L11
