### ISSUE TITLE
能否新增自定义上传网站icon

### ISSUE THREAD

**Issue by MatrixShoo** [NoCLin/WebAppify#2]
很开心能够使用你开发的功能，体验是非常好的，下面有一点建议，希望你能采纳。
注意到现在是自动获取网站的icon，但是获取的好像是有背景的图片，在显示上面就会很突兀。如下图所示，他是带有白色背景的：
![image.png](https://s2.loli.net/2023/06/13/FWHjVXfmYEip4Zh.png)

能否增加我们自定义上传icon的功能，或者程序能够自动获取到没有背景的icon。
谢谢，这是个建议！

**Comment by NoCLin** [comment]
Hi @MatrixShoo , 建议已收到，我会在非工作时间处理，预计周末可以发布新版本

**Comment by NoCLin** [comment]
Done. https://github.com/NoCLin/WebAppify/commit/e200e0d31c0d45198a6129484b3aa6137194a6b0

@MatrixShoo

**Comment by MatrixShoo** [comment]
> Done. [e200e0d](https://github.com/NoCLin/WebAppify/commit/e200e0d31c0d45198a6129484b3aa6137194a6b0)
> 
> @MatrixShoo

已使用上，非常感谢！
